name = input("Enter student name here")
maths = input("What did you get in Maths?")
english = input("What did you get in English?")
spanish = input("What did you get in Spanish?")
physics = input("What did you get in Physics?")
total = int(maths) + int(english) + int(spanish) + int(physics)
print(total)